### ISSUE TITLE
Edit to do error

### ISSUE THREAD

**Issue by Oliversw** [FACxBeamery/project-week-3#39]
On using Postman to call the `http://localhost:3000/edittodo` route, the server crashes with the following error:
```
/Users/Oliver/Dropbox/Coding/beamery/project-week-3/src/router.js:89
    parsedTodos = pf.editArray(parsedTodos, id, newTitle, date.Now());
                                                          ^

ReferenceError: date is not defined
    at editTodo (/Users/Oliver/Dropbox/Coding/beamery/project-week-3/src/router.js:89:59)
    at /Users/Oliver/Dropbox/Coding/beamery/project-week-3/src/router.js:11:13
```

Changing it to a capital (`Date.now`) also throws an error:
```
/Users/Oliver/Dropbox/Coding/beamery/project-week-3/src/router.js:89
    parsedTodos = pf.editArray(parsedTodos, id, newTitle, Date.Now());
                                                               ^

TypeError: Date.Now is not a function
    at editTodo (/Users/Oliver/Dropbox/Coding/beamery/project-week-3/src/router.js:89:64)
    at /Users/Oliver/Dropbox/Coding/beamery/project-week-3/src/router.js:11:13
```

**Comment by Joaoviana** [comment]
pls pull the repo again. 🐛 has been fixed
